### ISSUE TITLE
Cyber Summer

### ISSUE THREAD

**Issue by rcmanglona** [FreeCodeCampGuam/FreeCodeCampGuamHelp#9]
I found a couple of links that might be useful for Cyber Summer. The first is a link to an article about Bootstrap and the second is to the organization itself. Bootstrap offers two different curricula that are aligned with Common Core Math standards for middle and high school. The program is also supported by the National Science Foundation and has several links to research about its impact and effectiveness. 

We could use their curricula and adapt them to use FreeCodeCamp and use their research as a defense for learning math through programming. Bootstrap's materials are also supposedly free, so we might consider the program as an alternative to FCC for the camp (Considering we're pressed for time in developing a course.). 

[Free Game Programming Curriculum Invades Math Classes](https://campustechnology.com/articles/2014/05/01/free-game-programming-curriculum-invades-math-classes.aspx)
[Bootstrap](http://www.bootstrapworld.org/index.shtml)

**Comment by Chovin** [comment]
Nice find!
We may need to spruce it up a bit so that it covers high school math concepts though.
I agree that game programming is a great source of Math concepts.
The logic, physics, and graphics that go into it can get immensely complex!

Along those lines, I wonder if there are low-level graphics libraries available for easy-to-learn langauges like Java, JS, or Python
